name: todo
description: A minimalistic todo app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  intl: 0.18.1
  stacked: 3.4.1+1
  stacked_services: 1.3.0

dev_dependencies:
  build_runner: 2.4.6
  flutter_launcher_icons: 0.13.1
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.0
  stacked_generator: 1.5.1

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
